# Generated by Django 3.1.2 on 2020-10-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='US',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=200)),
                ('channel_title', models.CharField(max_length=200)),
                ('publish_time', models.CharField(max_length=200)),
                ('category_id', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
            ],
        ),
    ]
